feature/header
vern-gora/project-test-pr0ject pull request #4
Opened 2023-06-30 15:24 UTC by ProsukovOleksandr

HTML и CSS разметка хедера

2023-06-30 16:05 UTC, vern-gora requested changes

2023-06-30 16:05 UTC, vern-gora commented on src/css/header.css
> +    font-family: "DM Sans", sans-serif;
шрифт у тебя не правильно указан, можешь зайти в файл base.css и посмотреть как называются шрифты
`@font-face {
  font-family: DMSans-400;
  src: url(../fonts/DMSans-Regular.ttf);
}`
вот тут например `font-family: DMSans-400;` вот такое название

2023-06-30 16:05 UTC, vern-gora commented on src/css/header.css
> +  .logo svg{
размер свг указывай в html

2023-06-30 16:05 UTC, vern-gora commented on src/partials/header.html
> +      <path d="M15.8335 5.83335H13.3335V5.00002C13.3335 4.11596 12.9823 3.26812 12.3572 2.643C11.7321 2.01788 10.8842 1.66669 10.0002 1.66669C9.11611 1.66669 8.26826 2.01788 7.64314 2.643C7.01802 3.2
я сейчас добавлю в спрайт иконку поменяешь это

2023-07-01 09:28 UTC, ProsukovOleksandr commented on src/css/header.css
> +    font-family: "DM Sans", sans-serif;
Исправил

2023-07-01 09:28 UTC, ProsukovOleksandr commented on src/css/header.css
> +  .logo svg{
Исправил

2023-07-01 09:28 UTC, ProsukovOleksandr commented on src/partials/header.html
> +      <path d="M15.8335 5.83335H13.3335V5.00002C13.3335 4.11596 12.9823 3.26812 12.3572 2.643C11.7321 2.01788 10.8842 1.66669 10.0002 1.66669C9.11611 1.66669 8.26826 2.01788 7.64314 2.643C7.01802 3.2
Все поменял, теперь работает

2023-07-01 10:41 UTC, vern-gora approved these changes

2023-07-01 10:41 UTC, merged